### PR TITLE
Add myself

### PR DESCRIPTION
**Pull request by strk**
as per https://github.com/lunny/gitea/blob/33df11e82312e8306885c34d5125fcca1ba3dd9b/CONTRIBUTING.md
You can find my name in the commit log (not sure which PR number to reference here)

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
Yeah, test succeed.

**Comment by lunny** [comment]
sss

**Comment by lunny** [comment]
ffff

**Comment by lunny** [comment]
fsfdfs

**Comment by strk** [comment]
LGTM

**Comment by strk** [comment]
not in lunny/gitea/MAINTAINERS ?

**Comment by lunny** [comment]
This is a lgtm test. Please send pr to go-gitea

**Comment by strk** [comment]
Yeah, I figured, was trying to help testing :)

**Comment by lunny** [comment]
:)

**Pull request closed without merging**
